export const toSelectOptions = (items = []) =>
  items.map((item) => ({ value: item, label: item }));

export const Catalogo = {

  // Para las opciones en FromCIin y MedalDetalle

  Asunto: [
    "AMPARO",
    "COMPROBANTE IMSS",
    "ENTREGA BITACORAS",
    "INFORMES INVEA",
    "INSPECCIÓN OCULAR REPOSICIÓN DE SELLOS DE CLAUSURA",
    "INSPECCIÓN OCULAR Y REPOSICIÓN DE SELLOS DE SUSPENSIÓN",
    "JUICIO DE NULIDAD",
    "LISTA ASISTENCIA CAVA",
    "LISTA ASISTENCIA CVA",
    "LISTA ASISTENCIA DEVA",
    "NOTA INFORMATIVA",
    "NOTIFICACIÓN",
    "NOTIFICACIÓN DE ACUERDO",
    "NOTIFICACIÓN DE ACUERDO Y RETIRO DE SELLOS DEFINITIVO",
    "NOTIFICACIÓN DE ACUERDO Y RETIRO DE SELLOS PROVISIONAL",
    "NOTIFICACIÓN DE AUDIENCIA",
    "NOTIFICACIÓN DE CUMPLIMIENTO",
    "NOTIFICACIÓN DE FECHA DE ACUERDO",
    "REMITE INFORMACIÓN",
    "REPORTE MENSUAL",
    "REPOSICIÓN DE SELLOS DE CLAUSURA",
    "REPOSICIÓN DE SELLOS DE MEDIDAS CAUTELARES",
    "RESOLUCIÓN",
    "RESOLUCIÓN MULTA",
    "RESOLUCIÓN MULTA Y CLAUSURA",
    "RESOLUCIÓN MULTA, RETIRO DE SELLOS Y CLAUSURA",
    "RESOLUCIÓN SIN SANCIÓN",
    "RESOLUCIÓN SIN SANCIÓN Y RETIRO DE SELLOS",
    "RETIRO DE SELLOS",
    "RETIRO DE SELLOS JUZGADO DE DISTRITO 24 HORAS",
    "RETIRO DE SELLOS JUZGADO DE DISTRITO 3 DÍAS",
    "RETIRO DE SELLOS POR TJA 24 HORAS",
    "RETIRO DE SELLOS POR TJA 3 DÍAS",
    "RETIRO DE SELLOS POR TJA 5 DÍAS",
    "REUNIÓN EXTERNA",
    "REUNIÓN INTERNA",
    "SENSIBILIZACIÓN",
    "SOLICITA INFORMACIÓN",
    "SOLICITA INSPECCIÓN OCULAR",
    "SOLICITA VISITA DE VERIFICACIÓN",
    "SOLICITUD DE VACACIONES",
    "SOLICITUD GASOLINA EXTRAORDINARIA",
    "SOLICITUD GASOLINA ORDINARIA",
    "SOLICITUD OIC",
    "SOLICITUD TRANSPARENCIA",
    "VISITA COMPLEMENTARIA"
  ],

  Motivo: [
    "ACUERDO",
    "ANUNCIOS",
    "ATENCIÓN CIUDADANA",
    "AUDIENCIA CIUDADANA",
    "CARPETA DE INVESTIGACIÓN",
    "CASA POR CASA",
    "INTERNOS",
    "MEDIOS DIGITALES",
    "NOTIFICACIÓN CON SANCIÓN",
    "NOTIFICACIÓN SIN SANCIÓN",
    "OFICIALIA DE PARTES",
    "PAOT",
    "REMITE INFORMACIÓN",
  ],

  Caracter: [
    "ORDINARIO", 
    "URGENTE"
  ],

  TipoInmueble: [
    "Establecimiento",
    "Medios publicitarios",
    "Obra",
  ],

// Para los selects en Consulta

  SubDireccion: [
    "x",
    "y",
    "z",
  ],

  // Para las acciones de respuesta en RespuestaTurnado

  Accion: [
      "CONOCIMIENTO",
      "CONTESTACIÓN",
      "EJECUTADO",
      "INSPECCIÓN OCULAR",
      "NO EJECUTADO",
      "RECABACIÓN DE INFORMACION",
      "REMISION PARA GENERAR VV",
      "REPOSICÓN DE SELLOS",
      "RETIRO DE SELLOS",
      "SE INFORMA REPOSICIÓN DE SELLOS",
      "VISITA DE VERIFICACIÓN",
      "ZONIFICACION",
      "REMISIÓN A SUBSTANCIACIÓN",
      "REMISIÓN A JURIDICO",
      "SIN COMPETENCIA EN LA MATERIA",
      "DOMICILIO INCIERTO",
      "NO SE OBSERVAN ACTOS DENUNCIADOS",
  ],
};