export const toSelectOptions = (items = []) =>
  items.map((item) => ({ value: item, label: item }));

export const Catalogo = {

  // Para las opciones en FromCIin y MedalDetalle

  Asunto: [
    "AMPARO",
    "CONCEPTO",
    "INSPECCIÓN OCULAR REPOSICIÓN DE SELLOS DE CLAUSURA",
    "INSPECCIÓN OCULAR Y REPOSICIÓN DE SELLOS DE SUSPENSIÓN",
    "JUICIO DE NULIDAD",
    "NOTIFICACIÓN",
    "NOTIFICACIÓN DE ACUERDO",
    "NOTIFICACIÓN DE ACUERDO Y RETIRO DE SELLOS DEFINITIVO",
    "NOTIFICACIÓN DE ACUERDO Y RETIRO DE SELLOS PROVISIONAL",
    "NOTIFICACIÓN DE AUDIENCIA",
    "NOTIFICACIÓN DE CUMPLIMIENTO",
    "NOTIFICACIÓN DE FECHA DE ACUERDO",
    "REMITE INFORMACIÓN",
    "REPOSICIÓN DE SELLOS DE CLAUSURA",
    "REPOSICIÓN DE SELLOS DE MEDIDAS CAUTELARES",
    "RESOLUCIÓN",
    "RESOLUCIÓN MULTA",
    "RESOLUCIÓN MULTA Y CLAUSURA",
    "RESOLUCIÓN MULTA, RETIRO DE SELLOS Y CLAUSURA",
    "RESOLUCIÓN SIN SANCIÓN",
    "RESOLUCIÓN SIN SANCIÓN Y RETIRO DE SELLOS",
    "RETIRO DE SELLOS",
    "RETIRO DE SELLOS JUZGADO DE DISTRITO 24 HORAS",
    "RETIRO DE SELLOS JUZGADO DE DISTRITO 3 DÍAS",
    "RETIRO DE SELLOS POR TJA 24 HORAS",
    "RETIRO DE SELLOS POR TJA 3 DÍAS",
    "RETIRO DE SELLOS POR TJA 5 DÍAS",
    "SOLICITA INFORMACIÓN",
    "SOLICITA INSPECCIÓN OCULAR",
    "SOLICITA VISITA DE VERIFICACIÓN",
  ],

  Motivo: [
    "ACUERDO",
    "ANUNCIOS",
    "ATENCIÓN CIUDADANA",
    "AUDIENCIA CIUDADANA",
    "CARPETA DE INVESTIGACIÓN",
    "CASA POR CASA",
    "INTERNOS",
    "MEDIOS DIGITALES",
    "NOTIFICACIÓN CON SANCIÓN",
    "NOTIFICACIÓN SIN SANCIÓN",
    "OFICIALIA DE PARTES",
    "PAOT",
    "REMITE INFORMACIÓN",
  ],

  Caracter: [
    "ORDINARIO", 
    "URGENTE"
  ],

  TipoInmueble: [
    "Establecimiento",
    "Medios publicitarios",
    "Obra",
  ],

// Para los selects en Consulta

  SubDireccion: [
    "x",
    "y",
    "z",
  ],

  // Para las acciones de respuesta en RespuestaTurnado

  Accion: [
      "CONOCIMIENTO",
      "CONTESTACIÓN",
      "EJECUTADO",
      "INSPECCIÓN OCULAR",
      "NO EJECUTADO",
      "RECABACIÓN DE INFORMACION",
      "REMISION PARA GENERAR VV",
      "REPOSICÓN DE SELLOS",
      "RETIRO DE SELLOS",
      "VISITA DE VERIFICACIVISITA DE VERIFICACION",
      "ZONIFICACION",
  ],
};